### ISSUE TITLE
download_data.sh  VERED_REPO_URL&KIMANH_REPO_URL 404 not found

### ISSUE THREAD

**Issue by lemonadeseason** [facebookresearch/hypernymysuite#12]
Would you please undate  valid url？Thanks a lot

**Comment by stephenroller** [comment]
https://github.com/vered1986/UnsupervisedHypernymy/tree/master/datasets you can find the data here, but I don't have time to dig into what's wrong with the download script

**Comment by lemonadeseason** [comment]
> https://github.com/vered1986/UnsupervisedHypernymy/tree/master/datasets you can find the data here, but I don't have time to dig into what's wrong with the download script

Thanks a lot for your respose！And I have another question. I am reading your paper《hearst patterns revisited: automatic hypernym detection from large text corpora》, in section3.2: the experiment set up for distributional models, it said that you employed distributional space from Shwartz(2017), there are several kinds of distributional spaces in that paper, which one you employed in your work, is it "window-based, ppmi"?    In addition, I find that you used "hearst_counts.txt.gz" to construct distributional space in your code, which is different from the description from your paper, why?    
Looking forward to your response!

**Comment by stephenroller** [comment]
For the distributional baselines, like invCL and BalAPinc, we used Vered's spaces. For our own proposals, we used the Hearst counts

**Comment by lemonadeseason** [comment]
> For the distributional baselines, like invCL and BalAPinc, we used Vered's spaces. For our own proposals, we used the Hearst counts

thank you！
