### ISSUE TITLE
The $OMER_URL is unavailable

### ISSUE THREAD

**Issue by crystina-z** [facebookresearch/hypernymysuite#13]
Hi! The url (http://u.cs.biu.ac.il/~nlp/wp-content/uploads/lexical_inference.zip) in `download_data.sh` for `BLESS` and `LEDS` seems unavailable now. It returns 403 forbidden when trying to access. I wonder if there is any suggestion on a replacement? Thanks!

**Comment by unw9527** [comment]
Same concern. It seems that without these two files a lot codes need to be commented to run the program.

**Comment by stephenroller** [comment]
Has anyone found a mirror?

**Comment by stephenroller** [comment]
We've mirrored the data directly into the repo in #14.
