### ISSUE TITLE
Experimental results in paper is on val set or test set？

### ISSUE THREAD

**Issue by lemonadeseason** [facebookresearch/hypernymysuite#15]
"generate_table.sh" returns both Validation and test performance, so I'm confused which is the final result you presented in your paper.

**Comment by stephenroller** [comment]
I really can't remember, sorry. I would assume they are test results as we optimized the number of latent dimensions.

**Comment by lemonadeseason** [comment]
> I really can't remember, sorry. I would assume they are test results as we optimized the number of latent dimensions.

Thanks for your reply (*￣︶￣)
