### ISSUE TITLE
Hi,i tried to run download_data.sh but got error information like this: line 28: syntax error near unexpected token `&'

### ISSUE THREAD

**Issue by Lee-handsome** [facebookresearch/hypernymysuite#3]

**Comment by stephenroller** [comment]
Hi, maybe make sure you're running with `bash` and not `sh`. I suspect that feature might not be supported in plain shell.

Otherwise, please try to post any relevant information, like the exact command you ran and a copy-paste of output, maybe what version of bash you're using, etc.

**Comment by stephenroller** [comment]
Closing, please feel free to reopen if you need more help.
