### ISSUE TITLE
Portability to Mac OS

### ISSUE THREAD

**Issue by marthaflinderslewis** [facebookresearch/hypernymysuite#5]
Perhaps add to the readme that when running the file download_data.sh on macOS, it is necessary to ensure that you have the gnu versions of sort and sed installed. Two immediate problems with the native version are that macOS sort does not have the option random-sort, and macOS sed does not recognise \t as a tab.

**Comment by stephenroller** [comment]
Oh that's sad, I didn't realize those weren't supported on OS X. Unfortunately, I don't believe I have time to fix this, but I'd happily accept a PR to update the readme or update the scripts.

Thanks!

**Comment by stephenroller** [comment]
We've mirrored the data directly into the repo in #14.
