### ISSUE TITLE
hyperlex url is not available now

### ISSUE THREAD

**Issue by DiamondI** [facebookresearch/hypernymysuite#7]
The hyperlex url is not available now. It will show "The DS-Web service has been decommissioned" when visit the url. Could you offer the hyperlex data in this repo?

**Comment by stephenroller** [comment]
Thanks for flagging, We’re looking into it

**Comment by stephenroller** [comment]
Okay, I updated the URL to `https://github.com/ivulic/hyperlex/raw/master/hyperlex-data.zip` but didn't test it. Lemme know if still has problems.

**Comment by DiamondI** [comment]
It's strange that when I try to download hyperlex-data using `https://github.com/ivulic/hyperlex/raw/master/hyperlex-data.zip` in your script, it will be redirected. But I can download this zip file directly by visiting the url with browser or just using `wget` and `curl` commands in terminal. Anyway, I have managed to setup the whole 7 datasets.

Thanks a lot!

**Comment by stephenroller** [comment]
Okay, I think I fixed the redirect too. Thanks!
